networks:
  safeline-ce:
    name: safeline-ce
    driver: bridge
    ipam:
      driver: default
      config:
      - gateway: 169.254.0.1
        subnet: 169.254.0.0/24
    driver_opts:
      com.docker.network.bridge.name: safeline-ce

services:
  postgres:
    container_name: safeline-postgres
    restart: always
    image: postgres:15.2
    volumes:
    - ./data/resources/postgres/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
    environment:
    - 'POSTGRES_USER=safeline-ce'
    - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?postgres password required}'
    networks:
      safeline-ce:
        ipv4_address: 169.254.0.2
    cap_drop:
    - net_raw
    command: [postgres, -c, max_connections=200]
  management:
    container_name: safeline-mgt-api
    restart: always
    image: chaitin/safeline-mgt-api:1.6.0
    volumes:
    - ./data/resources/management:/resources/management
    - ./data/resources/nginx:/resources/nginx
    - ./data/logs:/logs
    - /etc/localtime:/etc/localtime:ro
    ports:
    - '{{ports.management.ip}}:{{ports.management.port}}:1443'
    environment:
    - 'MANAGEMENT_RESOURCES_DIR=/resources/management'
    - 'NGINX_RESOURCES_DIR=/resources/nginx'
    - 'DATABASE_URL=postgres://safeline-ce:${POSTGRES_PASSWORD}@127.0.0.1/safeline-ce'
    - 'MANAGEMENT_LOGS_DIR=/logs/management'
    networks:
      safeline-ce:
        ipv4_address: 169.254.0.4
    cap_drop:
    - net_raw
  detector:
    container_name: safeline-detector
    restart: always
    image: chaitin/safeline-detector:1.6.0
    volumes:
    - ./data/resources/detector:/resources/detector
    - ./data/logs/detector:/logs/detector
    - /etc/localtime:/etc/localtime:ro
    environment:
    - 'LOG_DIR=/logs/detector'
    networks:
      safeline-ce:
        ipv4_address: 169.254.0.5
    cap_drop:
    - net_raw
  mario:
    container_name: safeline-mario
    restart: always
    image: chaitin/safeline-mario:1.6.0
    volumes:
    - ./data/resources/mario:/resources/mario
    - ./data/logs/mario:/logs/mario
    - /etc/localtime:/etc/localtime:ro
    environment:
    - 'LOG_DIR=/logs/mario'
    - 'GOGC=100'
    - 'DATABASE_URL=postgres://safeline-ce:${POSTGRES_PASSWORD}@169.254.0.2/safeline-ce'
    networks:
      safeline-ce:
        ipv4_address: 169.254.0.6
    cap_drop:
    - net_raw
  tengine:
    container_name: safeline-tengine
    restart: always
    image: chaitin/safeline-tengine:1.6.0
    volumes:
    - ./data/resources/nginx:/etc/nginx
    - ./data/resources/management:/resources/management
    - ./data/resources/detector:/resources/detector
    - ./data/logs/nginx:/var/log/nginx
    - /etc/localtime:/etc/localtime:ro
    - ./data/resources/cache:/usr/local/nginx/cache
    - /etc/resolv.conf:/etc/resolv.conf
    ulimits:
      nofile: 131072
    network_mode: host
